### ISSUE TITLE
Audio.Filter stops working when input exceed the range [-1,1]

### ISSUE THREAD

**Issue by sunep** [vvvv/VL.Audio#27]
works again if node is deleted and deletion is undone

**Comment by joreg** [comment]
can you provide a demo patch for this?

**Comment by sunep** [comment]
yep here you do.
[FilterDiesWhenLoud.zip](https://github.com/vvvv/VL.Audio/files/13459442/FilterDiesWhenLoud.zip)
Explanation:
When you multiply a sound by 20 or mor, it kills the filter, not the rest of the audio chain.

EDIT: I had to zip the file to add it.

**Comment by joreg** [comment]
thanks. fixed in upcoming release
