### ISSUE TITLE
Gamma crashes when changing samplerate

### ISSUE THREAD

**Issue by sunep** [vvvv/VL.Audio#3]
WHen trying to change samplerate in the audio engine, gamma crashes.

**Comment by sunep** [comment]
could be related to this issue https://github.com/tebjan/VVVV.Audio/issues/166

**Comment by sunep** [comment]
Same behavior in 2020.2.2 and "2020.3.0-0039-gd5d120d3b2 preview"

**Comment by joreg** [comment]
cannot reproduce in latest previews (>=0.3.0)
