### ISSUE TITLE
AudioEngine - Dynamic enum not set on startup

### ISSUE THREAD

**Issue by michael-burk** [vvvv/VL.Audio#5]
When I set the Sample Rate to e.g. 48000 kHz as an enum, this isn't applied on startup. I have to manually set the enum to something else and back for it to apply.

**Comment by joreg** [comment]
please always mention which exact vvvversion you're experiencing this with

**Comment by michael-burk** [comment]
2020.3.0-0071 and all before.

**Comment by azeno** [comment]
Same behavior with 2020.2.2 - so it's not the rewritten cache region at least. I suspect the dynamic enum.

**Comment by michael-burk** [comment]
Yes that's what I am suspecting, the enum is definitely buggy. It seems it get's created after it' supposed to be used. The Wrappe node also is displayed red, but there is no error. The enum is red, in some situations aswell.

**Comment by azeno** [comment]
I took the liberty to rename the issue.

**Comment by sunep** [comment]
This is also an issue in beta. The sample rate enum has a weird behavior there too.

EDIT: see https://github.com/tebjan/VVVV.Audio/issues/166
And
https://github.com/tebjan/VVVV.Audio/issues/173

**Comment by joreg** [comment]
this is fixed in 0.3.0
