### ISSUE TITLE
Add support for WASAPI

### ISSUE THREAD

**Issue by YanYas** [vvvv/VL.Audio#9]
As mentioned [here](https://discourse.vvvv.org/t/vl-audio-wasapi/18898/6) vl audio relies upon ASIO drivers which are not always convenient to install and are not as widely available as WASAPI drivers which are built in to Windows since Win 8.
We would be able to distribute software more easily and perhaps share audio resources without crashes if the option were added.

**Comment by joreg** [comment]
latest releases now support WASAPI
